version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prod:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - app
  api:
    image: lidoravitan/webit-backend
    environment:
      NODE_ENV: "production"
  app:
    image: lidoravitan/webit-frontend
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  wordpress:
    image: wordpress
    ports:
        - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: sql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  sql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql:delegated

  volumes:
    wordpress:
    db:
  