version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prod:/etc/nginx/conf.d
      - ./letsencrypt/live:/etc/letsencrypt
    depends_on:
      - api
      - app
  api:
    image: lidoravitan/webit-backend
    environment:
      NODE_ENV: "production"
  app:
    image: lidoravitan/webit-frontend
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db