version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./prod:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - app
  api:
    image: lidoravitan/webit-backend
    environment:
      NODE_ENV: "production"
  app:
    image: lidoravitan/webit-frontend-ssr
  admin:
      image: lidoravitan/webit-admin
  
  test-js:
    image: lidoravitan/webit-test-empty-javascript
  test-ts:
    image: lidoravitan/webit-test-empty-typescript
  test-api-ts:
    image: lidoravitan/webit-test-api-typescript
  test-api-js:
    image: lidoravitan/webit-test-api-javascript

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
