version: "3"
services:
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - app
  api:
    image: lidoravitan/webit-backend
    environment:
      NODE_ENV: "production"
  app:
    image: lidoravitan/webit-frontend
  admin:
      image: lidoravitan/webit-admin

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
