version: "3"
services:
  nginx:
    image: nginx:latest
    ports: 
        - 80:80
    volumes:
        - ./nginx:/etc/nginx/conf.d
  app: 
    image: lidoravitan/webit-frontend
  server: 
    image: lidoravitan/webit-backend
  db:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ./data/db:/data/db

    